apiVersion: v1
kind: Namespace
metadata:
  name: http-echo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-echo
  namespace: http-echo
spec:
  replicas: 5
  selector:
    matchLabels:
      app: http-echo
  template:
    metadata:
      labels:
        app: http-echo
    spec:
      containers:
      - image: hashicorp/http-echo:latest
        imagePullPolicy: IfNotPresent
        name: http-echo
        args: ["-text", "Hola CARLA 2024"]
        ports:
        - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: http-echo
  namespace: http-echo
spec:
  ports:
    - port: 80
      targetPort: 5678
      protocol: TCP
  type: ClusterIP
  selector:
    app: http-echo
---
# The below will not work out-of-the-box for Kind clusters, but would on a cloud provider.
#
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: http-echo
#  namespace: http-echo
#  annotations:
#    kubernetes.io/ingress.class: nginx
#spec:
#  rules:
#  - http:
#      paths:
#      - path: /
#        pathType: Prefix
#        backend:
#          service:
#            name: http-echo
#            port:
#              number: 80
